"""users table

Revision ID: a54f78201348
Revises: 
Create Date: 2025-03-10 20:22:50.180218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54f78201348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('weather_data_point',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('sunrise_time', sa.Time(), nullable=True),
    sa.Column('sunset_time', sa.Time(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('dew_point', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Integer(), nullable=False),
    sa.Column('wind_chill', sa.Float(), nullable=False),
    sa.Column('heat_index', sa.Float(), nullable=False),
    sa.Column('thw_index', sa.Float(), nullable=False),
    sa.Column('barometer', sa.Float(), nullable=False),
    sa.Column('rain_rate', sa.Float(), nullable=False),
    sa.Column('solar_radiation', sa.Integer(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_table('weather_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=12), nullable=True),
    sa.Column('longitutde', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_station', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_station_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_station_name'))

    op.drop_table('weather_station')
    op.drop_table('weather_data_point')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
